#!/usr/bin/bash

set -e

echo "\nBefore running this app you need sudo downloaded or have root privileges"

sleep 3

sudo pacman -Syu
[ ! -d ~/.config/fish ] && mkdir -p ~/.config/fish
mv ./fish ~/.config/fish/

echo "\nDone with fish\n"

# moving all files inside dots out into home directory?
echo "\nMoving files into home\n"
shopt -s dotglob; mv ./* ../

echo "\nDone moving files into home\n"

echo "\nDownloading through pacman...\n"

sudo pacman -S grim expac imagemagick breeze breeze-icons gdu qt6-virtualkeyboard eza exa zsh brightnessctl xplr networkmanager hyprland qbittorrent nwg-look gimp inkscape mission-center imv cliphist proton-vpn-cli dunst wireplumber tmux openssh mosh vim lazygit git github-cli glab blueman wine less ttf-jetbrains-mono-nerd unzip unrar tree-sitter-cli gcc make rsync fzf nodejs pnpm waybar rofi fish sddm kitty gsettings-qt6 dolphin ark neovim xfce4 vlc xfce4-terminal network-manager-applet flameshot shotcut audacity awww blender krita kdeconnect pipewire man swaylock pamixer virtualbox virtualbox-host-modules-arch komikku copyq qt6-declarative qt6-svg qt6-base qt5ct qt6ct-kde xdg-desktop-portal-gtk ttf-dejavu ttf-liberation noto-fonts adobe-source-code-pro-fonts adobe-source-sans-fonts adobe-source-serif-fonts

echo "\nDone with pacman\n"

echo "\nDownloading paru\n"
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
echo "\nDone downloading paru\n"

echo "\nDownlading through paru\n"
paru -S webcord-equicord-git brave-bin caffeine-ng-git wlogout hypremoji awww-bin
echo "Done with paru\n"

echo "\nDownloading sddm theme\n"
git clone https://github.com/ADIOR-enigma/hypr-sddm.git
cd hypr-sddm
sudo ./install.sh
cd ../

echo "\nDone downloading sddm theme\n"

echo "Downloading nvchad nvim plugin"
# Linux / MacOS (unix)
rm -rf ~/.config/nvim
rm -rf ~/.local/state/nvim
rm -rf ~/.local/share/nvim

git clone https://github.com/NvChad/starter ~/.config/nvim && nvim
echo "Done downloading nvim plugin"

echo "moving custom scripts to /usr/local/bin"
sudo mv ~/src/myScripts/* /usr/local/bin

echo "done moving custom scripts to /usr/local/bin"

# use own config hyrp
[ ! -d ~/.config/hypr ] && mkdir -p ~/.config/hypr
cp -r ~/components/hypr/{hyprland.conf,scripts} ~/.config/hypr

# waybar component
[ ! -d ~/.config/waybar] && mkdir -p ~/.config/waybar

cp -r ~/components/waybar ~/.config/waybar

echo "installed waybar"

# font
sudo fc-cache -fv

# Global GTK3/4 font
echo "setting up font for GTK3/4 apps"
gsettings set org.gnome.desktop.interface font-name 'Noto Sans CJK HK Regular 12'

# GTK2 (older apps)
echo "setting up font for GTK2 apps"
echo "gtk-font-name=Noto Sans CJK HK Regular 12" >> ~/.gtkrc-2.0

# Permanent (Fish config.fish)
echo 'set -gx QT_FONT_NAME "Noto Sans CJK HK Regular 12"' >> ~/.config/fish/config.fish

# Edit config
echo "setting up font for kitty"
[ ! -f ~/.config/kitty ] && mkdir -p ~/.config/kitty
echo 'font_family JetBrainsMono Nerd Font Mono' >> ~/.config/kitty/kitty.conf
echo 'font_size 12' >> ~/.config/kitty/kitty.conf

# enabling sddm
echo "\n enabling sddm\n"
sudo systemctl enable sddm
echo "done with downloading and setting up fonts"

# enabling audio
echo "enabling audio"
systemctl --user enable --now pipewire pipewire-pulse wireplumber
systemctl --user status pipewire pipewire-pulse wireplumber

echo "done with audio"

echo "sending gdu.desktop to /usr/local/bin so rofi can see it"
[ ! -d /usr/share/applications ] && sudo mkdir -p /usr/share/applications
mv ~/components/gdu.desktop /usr/share/applications
echo "done with gdu setup"

echo "setting up virtualbox"
sudo modprobe vboxdrv
echo "done with virtualbox"

echo "I highly recommend you to setup timeshift yourself"

echo "\n now you can bring bck your stuff youve backed uplike notes from elsewhere"

echo "also remember to reboot system and restart kitty"
