#!/usr/bin/bash

set -e

echo "\nBefore running this app you need sudo downloaded or have root privileges"

sleep 3

sudo pacman -Syu
mv config.fish ~/.config/fish/config.fish
sleep 2

echo "\nDone with fish\n"

# moving all files inside dots out into home directory?
echo "\nMoving files into home\n"
shopt -s dotglob; mv ./* ../

echo "\nDone moving files into home\n"

echo "\nDownloading through pacman...\n"

sudo pacman -S zsh brightnessctl networkmanager hyprland qbittorrent nwg-look gimp inkscape mission-center imv cliphist proton-vpn-cli dunst wireplumber tmux openssh mosh git github-cli glab blueman wine less ttf-jetbrains-mono-nerd unzip unrar tree-sitter-cli gcc make rsync timeshift ollama fzf nodejs pnpm waybar rofi fish sddm kitty gsettings-qt6 dolphin ark neovim xfce4 vlc xfce4-terminal network-manager-applet flameshot shotcut audacity awww blender krita kdeconnect pipewire man swaylock pamixer virtualbox discord komikku copyq qt6-declarative qt6-svg qt6-base

echo "\nDone with pacman\n"

echo "\ndownloading yay \n"
sudo pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

echo "\nDownlading through yay\n"
yay -S brave-bin caffeine-ng-git wlogout webcord-equicord-git hypremoji
echo "Done with yay\n"

echo "\nDownloading paru\n"
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
echo "\nDone downloading paru\n"

echo "\nDownloading sddm theme\n"
git clone https://github.com/ADIOR-enigma/hypr-sddm.git
cd hypr-sddm
sudo ./install.sh
cd ../

echo "\nDone downloading sddm theme\n"

echo "Downloading nvchad nvim plugin"
# Linux / MacOS (unix)
rm -rf ~/.config/nvim
rm -rf ~/.local/state/nvim
rm -rf ~/.local/share/nvim

git clone https://github.com/NvChad/starter ~/.config/nvim && nvim
echo "Done downloading nvim plugin"

echo "moving custom scripts to /usr/local/bin"
mv ~/src/myScripts/* /usr/local/bin

echo "done moving custom scripts to /usr/local/bin"

# use own config hyrp
cp -r ~/components/hypr/{hyprland.conf,scripts} ~/.config/hypr

# waybar config of the modular ones
cp -r ~/components/waybar ~/.local/share/waybar

# waybar component
cp -r ~/components/waybar2 ~/.config/waybar

echo "installed waybar"

# font
sudo fc-cache -fv

# Global GTK3/4 font
echo "setting up font for GTK3/4 apps"
gsettings set org.gnome.desktop.interface font-name 'JetBrainsMono Nerd Font Regular 11'

# GTK2 (older apps)
echo "setting up font for GTK2 apps"
echo "gtk-font-name=JetBrainsMono Nerd Font Regular 11" >> ~/.gtkrc-2.0

# Permanent (Fish config.fish)
echo 'set -gx QT_FONT_NAME "JetBrainsMono Nerd Font Regular 11"' >> ~/.config/fish/config.fish

# Edit config
echo "setting up font for kitty"
echo 'font_family JetBrainsMono Nerd Font Mono' >> ~/.config/kitty/kitty.conf
echo 'font_size 12' >> ~/.config/kitty/kitty.conf

echo "done with downloading and setting up fonts"

echo "I highly recommend you to setup timeshift yourself"

echo "\n now you can bring bck your stuff youve backed uplike notes from elsewhere"

echo "also remember to reboot system and restart kitty"

echo "Can safely change shell right now"
