#!/bin/fish
set is_charging ""
set battery_dir "/sys/class/power_supply/BAT0/"

while true
 set battery_capacity (cat $battery_dir/capacity)
 set battery_status (cat $battery_dir/status)

# if battery low
 if test $battery_capacity -lt 20; and test "$battery_status" = "Discharging"
  notify-send -w -u "critical" "Your battery is low." "Please plug in charger" 
 else if test $battery_capacity -lt 5;  and test "$battery_status" = "Discharging"
  notify-send -w -u "critical" "Your battery is EXTREMELY low." "Please plug in charger. The PC will automatically sleep soon" 
 else if test "$battery_status" = "Charging"; and test "$is_charging" != "true"
  notify-send "Charging"
  set is_charging "true" 
 else if test "$is_charging" = "true"; and test "$battery_status" = "Discharging"
   notify-send "Disconnected"
   set is_charging "false"
 else if test "$is_charging" = "true"; and test $battery_capacity -gt 84
   notify-send "Battery is full" "Charging has automatically stopped"
   set is_charging "false"
 end

end
