#!/bin/bash

ln-break() {
	echo -e "\n"
}

kf=2

targetBloodSugar=6

ik=10

ln-break

read -p "How much grams carb did you eat: " CARBS

ln-break

read -p "Whats your current blood sugar? (no decimals, mmol/l): " BS


difference=$(($BS - $targetBloodSugar))

correction=$(($difference / $kf))

food_insulin=$(($CARBS / $ik))

total_insulin=$(($food_insulin + $correction))

ln-break

echo "Result: $total_insulin"


