#!/bin/zsh

kf=2

targetBloodSugar=6

ik=10

CARBS=$(echo "" | rofi -dmenu -p "How much carbs eaten" -l 0)

BS=$(echo "" | rofi -dmenu -p "What's your blood sugar at" -l 0)

difference=$(($BS - $targetBloodSugar))

correction=$(($difference / $kf))

food_insulin=$(($CARBS / $ik))

total_insulin=$(($food_insulin + $correction))

notify-send "Result: $total_insulin"
