#!/bin/zsh

# tis app to first list all programs and show the unused ones. optional if it can delete them

# find packs and store in a vars, depending on what package manager the user has installed

[[ -f /bin/pacman ]] && pacman_packs=$(sudo pacman -Q)|| echo "\nPacman not found \n"

[[ -f /bin/dnf ]] && dnf_packs=$(dnf list installed) || echo "dnf not found"

[[ -f /bin/flatpak ]] && flatpak_packs=$(flatpak list) || echo "Flatpak not found"

#echo $pacman_packs
#echo $dnf_packs
#echo $flatpak_packs


# check bash and zsh history. find out their shell
shell_choice=$(echo $SHELL)

[[ zsh ]] && { 
	zsh_history=$(cat ~/.zsh_history)
} || echo "no zsh, checking bash"

[[ bash ]] && {
	bash_history=$(cat ~/.bash_history)
} || echo "no bash"

$zsh_history | grep $pacman_choice | less
