#!/bin/zsh

[[ $# == 0 ]] && {
	echo "error no input written: lsgrep <filewant grepped> <path to look through(optional)>"
	return 1
}

search="$1"
path="${2:-.}"

[[ "$2" != ""  ]] && {
	echo "your path is $path: "
 } || {
	echo "searching for $search: "
 }

/usr/bin/ls "$path" | /usr/bin/grep "$search"

# for variables. parameter expansion. if var 1 not exist use default value.
# ${var:-default}
