#!/bin/zsh

command -v less >/dev/null 2>&1 || {echo "You need to install 'less' "; exit 1;}

path="${1:-.}"

[[ -d "$path" ]] || { echo "Directory not found: $path"; exit 1; }


/usr/bin/ls "$path" | /usr/bin/less  

# idea: ls $var | less
# idea 2: ls $var -la | less
# idea 2: ls $var -l | less
# idea 3: ls $var -a | less
