#!/bin/bash

if [[ $# -lt 0 ]]; then

	echo "Usage: mkal <alias name> <cmd wanna replace in one string>"
	exit 1
fi

sudo echo -e "\n alias $1='$2'" | sudo tee -a ".zshrc" > /dev/null

echo -e " \n If everything went right, run: sudo source ~/.zshrc"
