#!/bin/bash

# $0 inputs the path of the file

if [[ $# -eq 0 ]]; then
   echo "Usage: mkdev <script name>"
   exit 1

fi

SCRIPT_PATH="/usr/local/bin/$1"

sudo echo -e "#!/bin/zsh\n" | sudo tee "$SCRIPT_PATH" > /dev/null 

sudo chmod +wx "$SCRIPT_PATH"
sudo chown astro "$SCRIPT_PATH"

sudo vim "$SCRIPT_PATH"

echo "Script created: $SCRIPT_PATH"
