#!/bin/zsh

# path
NOTE_PATH='/home/astro/inbox/inbox.md'

[[ $# == 0 ]] && { notify-send "Right usage: nn '<text that you want added>'" || echo "Right usage: nn '<text that you want added>'"; exit 1 }

echo "- $1"  >> $NOTE_PATH

notify-send "note added" || echo "Note added"
