#!/bin/sh

action=$1

case $action in 
   turn-up)
      brightnessctl set +10%
      bright=$(brightnessctl i | grep -o -E '[0-9][0-9]%')
      notify-send -r 7777 "Backlight" "$bright" -h int:value:$bright -i notification-display-brightness-full
  ;;
  turn-down)
    brightnessctl set 10%-
    bright=$(brightnessctl i | grep -o -E '[0-9][0-9]%')
    notify-send -r 7777 "Backlight" "$bright" -h int:value:$bright -i notification-display-brightness-low
  ;;
esac
