foreground              #0D0D0D
background              #959DC7
selection_foreground    #959DC7
selection_background    #0D0D0D
cursor                  #16171F
cursor_text_color       #FFFFFF

active_tab_foreground     #959DC7
active_tab_background     #24283B
inactive_tab_foreground   #24283B
inactive_tab_background   #959DC7

# black
color0      #292F52
color8      #57608F

# red
color1      #CCD2FF
color9      #AAB2F0

# green
color2      #CCD8FF
color10     #AABAF0

# yellow
color3      #CCD5FF
color11     #AAB6F0

# blue
color4      #9AA6E6
color12     #9AA6E6

# magenta
color5      #9AABE6
color13     #9AABE6

# cyan
color6      #9AA7E6
color14     #9AA7E6

# white
color7      #CCD2FF
color15     #AAB2F0
